name: irrigtrack
services:
  - name: frontend
    source_dir: frontend-vue
    github:
      repo: your-username/irrigtrack
      branch: main
    build_command: npm install && npm run build
    run_command: npx serve -s dist -l $PORT
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: VITE_API_BASE_URL
        scope: BUILD_TIME
        value: ${backend.URL}/api
      - key: VITE_PY_API_BASE_URL
        scope: BUILD_TIME
        value: ${python-api.URL}
      - key: VITE_PUSHER_APP_KEY
        scope: BUILD_TIME
        value: ${backend.REVERB_APP_KEY}

  - name: backend
    source_dir: backend-laravel
    github:
      repo: your-username/irrigtrack
      branch: main
    build_command: composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan storage:link
    run_command: php artisan serve --host=0.0.0.0 --port=$PORT
    environment_slug: php
    instance_count: 1
    instance_size_slug: basic-xxs

  - name: python-api
    source_dir: .
    github:
      repo: your-username/irrigtrack
      branch: main
    build_command: pip install -r requirements.txt
    run_command: python ml_api_server.py
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs

